name: Release & Publish

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  id-token: write

jobs:
  release:
    name: Build, Release & Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      # 1. check build and test
      - name: Typecheck & Build
        run: |
          npx tsc -b --noEmit
          npm run build
          npm test

      # 2. sync version package.json and tag name (bump)
      - name: Set package.json version from tag
        run: |
          # Извлекаем версию без буквы 'v' (из v1.2.3 получаем 1.2.3)
          VERSION=${GITHUB_REF_NAME#v}
          echo "Bumping package.json to $VERSION"
          npm version $VERSION --no-git-tag-version

      # 3. NPM public
      - name: Publish to npm
        working-directory: ./cli
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # 4. create GitHub Release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
